title: "Cozy Cafe Corner"
description: "Specializing in IT solutions, web development, and infrastructure maintenance for your business."
images: 
  - "images/hero-image.png"

logo: "logo.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

# social:
#   dribbble: "#"
#   instagram: "#"
#   facebook: "#"
#   twitter: "#"

location:
  - "Richmond, BC, Canada"

contact:
  - "jerrysun.work@hotmail.com"

copyright: "© 2026 Cozy Cafe Corner All Rights Reserved"

